### ISSUE TITLE
The Composer configuration file is missing.

### ISSUE THREAD

**Issue by ghost** [nmarulo/softn-cms#8]
After reviewing the project structure, I've noticed you're already using the Composer's autoload feature, but I couldn't find the `composer.json` file.

Without that file, you won't be able to publish your project in [Packagist](https://packagist.org/), and nobody will be able to extend your project neither.

**Comment by nmarulo** [comment]
This project can not be found in "**Packagist**", because it is not a package or a component that you can add to an application, because it is already an application. (Later on, I plan to split the application into modules, this way if it can be in "Packagist")

In the "**master**" branch will be all the necessary files for the operation of the application.

In the "**develop**" branch you can find the file ["`composer.json`".](https://github.com/nmarulo/softn-cms/blob/develop/composer.json)

To contribute to this project you can use the "**Fork**" button. This project is licensed "**MIT**" you are free to make any changes under the same license.

**Comment by ghost** [comment]
Yes, you're right. I was watching your last modified branch, without checking the other ones.

I'm closing this issue.

**Comment by nmarulo** [comment]
Ok, I'm going to change this anyway. I think I got it wrong, and the "master" branch should not include all dependencies. Best I will add an external download with the application, including all dependency and ready to use.

Thanks for comment.
